on:
  push:
    branches:
      - master
name:                          Tfaction
jobs:
  test-terraform-code:
    name:                      Tfaction
    runs-on:                   ubuntu-18.04
    env:
      TF_VAR_compartment_ocid: ${{ secrets.TF_VAR_compartment_ocid }}
      TF_VAR_fingerprint:      ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_private_key:      ${{ secrets.TF_VAR_private_key }}
      TF_VAR_tenancy_ocid:     ${{ secrets.TF_VAR_tenancy_ocid }}
      TF_VAR_user_ocid:        ${{ secrets.TF_VAR_user_ocid }}
      TF_VAR_PASS:             ${{ secrets.TF_VAR_PASS }}
    steps:
    - name:                    Checkout
      uses:                    actions/checkout@master
    - name:                    Terraform Apply
      uses:                    "terraform-oci-vcn/terraform-oci-vcn/actions/terraform-apply@master"
