name: Terraform CI

on: 
  push:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    env:
      TF_VAR_compartment_id:   ${{ secrets.TF_VAR_compartment_ocid }}
      TF_VAR_fingerprint:      ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_private_key:      ${{ secrets.TF_VAR_private_key }}
      TF_VAR_private_key_path: $GITHUB_WORKSPACE/oci.pem
      TF_VAR_tenancy_ocid:     ${{ secrets.TF_VAR_tenancy_ocid }}
      TF_VAR_user_ocid:        ${{ secrets.TF_VAR_user_ocid }}
      TF_VAR_region:           ${{ secrets.TF_VAR_region }}
    steps:
    - name:                    Checkout
      uses:                    actions/checkout@v1
      
   - name: dummy
     uses: "terraform-oci-vcn/terraform-oci-vcn/actions/terraform-apply@master"
