name: Terraform CI

on: 
  push:
    branches:
      - master

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    env:
      TF_VAR_compartment_id:   ${{ secrets.TF_VAR_compartment_ocid }}
      TF_VAR_fingerprint:      ${{ secrets.TF_VAR_fingerprint }}
      TF_VAR_private_key:      ${{ secrets.TF_VAR_private_key }}
      #TF_VAR_private_key_path: $GITHUB_WORKSPACE/oci.pem
      TF_VAR_tenancy_ocid:     ${{ secrets.TF_VAR_tenancy_ocid }}
      TF_VAR_user_ocid:        ${{ secrets.TF_VAR_user_ocid }}
      TF_VAR_region:           ${{ secrets.TF_VAR_region }}
    steps:
    - name:                    Checkout
      uses:                    actions/checkout@v1
      
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Get dependencies
      run: |
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        else
          go get -v -d -t ./...  
        fi
      
    - name: Terratest
      working-directory: /home/runner/work/terraform-oci-vcn/terraform-oci-vcn/test
      env:
        TF_VAR_compartment_id:   ${{ secrets.TF_VAR_compartment_ocid }}
        TF_VAR_fingerprint:      ${{ secrets.TF_VAR_fingerprint }}
        TF_VAR_private_key:      ${{ secrets.TF_VAR_private_key }}
        #TF_VAR_private_key_path: $GITHUB_WORKSPACE/oci.pem
        TF_VAR_tenancy_ocid:     ${{ secrets.TF_VAR_tenancy_ocid }}
        TF_VAR_user_ocid:        ${{ secrets.TF_VAR_user_ocid }}
        TF_VAR_region:           ${{ secrets.TF_VAR_region }}
      run: sudo go test -v
